replicaCount: 1

image:
  repository: bhisek171/go-web-app-aws
  pullPolicy: IfNotPresent
  tag: "15802857667"

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific

